// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/articles": {
    params: {};
  };
  "/articles/new": {
    params: {};
  };
  "/articles/:id": {
    params: {
      "id": string;
    };
  };
  "/articles/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/editor": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/articles" | "/articles/new" | "/articles/:id" | "/articles/:id/edit" | "/editor";
  };
  "./components/Layout.tsx": {
    id: "components/Layout";
    page: "/" | "/articles" | "/articles/new" | "/articles/:id" | "/articles/:id/edit" | "/editor";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/articles.tsx": {
    id: "routes/articles";
    page: "/articles";
  };
  "routes/articles.new.tsx": {
    id: "routes/articles.new";
    page: "/articles/new";
  };
  "routes/articles.$id.tsx": {
    id: "routes/articles.$id";
    page: "/articles/:id";
  };
  "routes/articles.$id.edit.tsx": {
    id: "routes/articles.$id.edit";
    page: "/articles/:id/edit";
  };
  "routes/editor.tsx": {
    id: "routes/editor";
    page: "/editor";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "components/Layout": typeof import("./app/./components/Layout.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/articles": typeof import("./app/routes/articles.tsx");
  "routes/articles.new": typeof import("./app/routes/articles.new.tsx");
  "routes/articles.$id": typeof import("./app/routes/articles.$id.tsx");
  "routes/articles.$id.edit": typeof import("./app/routes/articles.$id.edit.tsx");
  "routes/editor": typeof import("./app/routes/editor.tsx");
};